### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by drramki** [brentp/vcfanno#10] opened 2015-11-02 15:47 UTC
I am trying to use vcfanno with kaviar database and I get 'panic: runtime error: index out of range'. Is this due to size of the database?

Here is the conf:

[[annotation]]
file="/PublicData/kaviar/Kaviar-150810-Public-hg19.vcf"
fields = ["AF"]
ops=["first"]

Here is the log:
=============================================
vcfanno version 0.0.7 [built with go1.5beta3]

see: https://github.com/brentp/vcfanno
=============================================
2015/11/02 10:41:20 found 1 sources from 1 files
panic: runtime error: index out of range

goroutine 5 [running]:
github.com/brentp/vcfgo.(*Variant).End(0xc8210c0960, 0x0)
        /usr/local/src/gocode/src/github.com/brentp/vcfgo/variant.go:104 +0xc7b
github.com/brentp/irelate.CheckOverlapPrefix(0x2aaaab4f7000, 0xc8210c0960, 0x2aaaab4f7000, 0xc8210c0a50, 0x0)
        /usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:96 +0x5b
github.com/brentp/irelate.IRelate.func1(0xc8200109c0, 0xbe5d38, 0xbe5d08, 0x0, 0xc820010a20)
        /usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:184 +0x4c9
created by github.com/brentp/irelate.IRelate
        /usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:217 +0xbf

goroutine 1 [chan receive]:
main.main()
        /usr/local/src/gocode/src/github.com/brentp/vcfanno/vcfanno.go:131 +0x1385

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [chan send]:
github.com/brentp/irelate.StreamVCF.func1(0xc8203099c0, 0xc8203687e0)
        /usr/local/src/gocode/src/github.com/brentp/irelate/vcf.go:53 +0x10b
created by github.com/brentp/irelate.StreamVCF
        /usr/local/src/gocode/src/github.com/brentp/irelate/vcf.go:61 +0x5d

goroutine 22 [runnable]:
github.com/brentp/vcfgo.(*Reader).Read(0xc820309c80, 0xc820368b40)
        /usr/local/src/gocode/src/github.com/brentp/vcfgo/reader.go:187 +0x89b
github.com/brentp/irelate.StreamVCF.func1(0xc820309c80, 0xc820368b40)
        /usr/local/src/gocode/src/github.com/brentp/irelate/vcf.go:49 +0x2e
created by github.com/brentp/irelate.StreamVCF
        /usr/local/src/gocode/src/github.com/brentp/irelate/vcf.go:61 +0x5d

goroutine 3 [chan receive]:
github.com/brentp/vcfanno/api.(*Annotator).Annotate.func1(0xc8201f5ab0, 0x2, 0x2, 0xc820010960, 0xc820178e40, 0x0, 0x0)
        /usr/local/src/gocode/src/github.com/brentp/vcfanno/api/api.go:421 +0x9f
created by github.com/brentp/vcfanno/api.(*Annotator).Annotate
        /usr/local/src/gocode/src/github.com/brentp/vcfanno/api/api.go:426 +0xb2

goroutine 4 [runnable]:
github.com/brentp/irelate.Merge.func1(0xc82000e480, 0xc8200109c0, 0xc82000a1b0, 0x0, 0xc8201f5ab0, 0x2, 0x2, 0x0)
        /usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:247 +0x1ba
created by github.com/brentp/irelate.Merge
        /usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:282 +0x3b2

**Comment by brentp** [comment] 2015-11-02 16:03
Hi, thanks for reporting, would you retry with the latest version from here: https://github.com/brentp/vcfanno/releases/tag/v0.0.8

you'll have to bgzip and tabix everything due to the parallelization, but it should either fix this error or give more informative message. Please let me know what you see.

**Comment by drramki** [comment] 2015-11-02 16:04
Thanks for the response. Does the annotation file need to be bgzipped as well?

**Comment by brentp** [comment] 2015-11-02 16:09
yes, it does. and tabixed. This aids in parallelization. Also, be sure to use at least 2 threads for annotation with `-p 2` .

**Comment by drramki** [comment] 2015-11-02 16:11
Thanks for this amazing tool. I tried 0.0.7 w/ exac and its amazingly fast. 25k variants annotated in less than 3 minutes. I might even be faster with more threads. Thanks again. I will update you after I try kaviar with 0.0.8

**Comment by brentp** [comment] 2015-11-02 17:09
great. let me know if you run into any other issues.

**Comment by drramki** [comment] 2015-11-02 21:14
v0.0.8 fixes the index out of range error. Thanks. I am closing this issue.

PS: How can we name an annotation field? for example, the ExAC and Kaviar, both have frequencies in AF field while my original vcf also has AF field. Right now, the original AF field is getting replaced by new value every time you annotate with an AF field. Is there a way to provide names?

**Comment by brentp** [comment] 2015-11-02 21:16
great. yes, you can add names. For each field, you add a corresponding name, see this file:
https://github.com/brentp/vcfanno/blob/master/example/gem.conf

for many examples, you can use, e.g.:

```
[[annotation]]
file="/PublicData/kaviar/Kaviar-150810-Public-hg19.vcf.gz"
fields = ["AF"]
names=["kaviar_af"]
ops=["first"]
``

**Comment by drramki** [comment] 2015-11-02 21:19
Thanks. I just realized that from the CADD example given. Thanks anyways~!

**Comment by drramki** [comment] 2015-11-03 19:07
Looks like this isn't gone in 0.0.8.

I was trying to annotate a vcf with ~120k variants using 4 different sources (exac, ESP, CADD and kaviar). It failed with a panic: index out of range error (error messages below). But it worked just fine when I split this by chromosome.

panic: runtime error: index out of range

goroutine 267510 [running]:
github.com/brentp/vcfgo.(*Variant).End(0xc2c9390680, 0x177fd18)
	/usr/local/src/gocode/src/github.com/brentp/vcfgo/variant.go:109 +0xd5e
github.com/brentp/irelate/interfaces.(*VarWrap).End(0xc25c51a5c0, 0xc20177fd19)
	<autogenerated>:24 +0x56
github.com/brentp/irelate.less(0x2aaab54f7828, 0xc26afa8230, 0x2aaab54733a0, 0xc25c51a5c0, 0x2aaab54f7828)
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:136 +0xc2
github.com/brentp/irelate.relatableQueue.Less(0xc267dbb180, 0x5, 0x5, 0xbdd338, 0x1, 0x0, 0xbdd338)
	/usr/local/src/gocode/src/github.com/brentp/irelate/relatableq.go:14 +0x87
github.com/brentp/irelate.(*relatableQueue).Less(0xc2abac90c8, 0x1, 0x0, 0x1)
	<autogenerated>:2 +0xb4
container/heap.up(0x2aaab54ef2d8, 0xc2abac90c8, 0x1)
	/usr/local/src/go/src/container/heap/heap.go:93 +0x5f
container/heap.Push(0x2aaab54ef2d8, 0xc2abac90c8, 0x9963c0, 0xc26afa8230)
	/usr/local/src/go/src/container/heap/heap.go:54 +0x7e
github.com/brentp/irelate.(*merger).Next(0xc2abac90a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:254 +0xa3d
github.com/brentp/irelate.(*irelate).Next(0xc2cd8580f0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/gocode/src/github.com/brentp/irelate/irelate.go:144 +0x89
github.com/brentp/irelate.func·003(0xc20d67e000, 0x5, 0x5)
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:218 +0x14c
created by github.com/brentp/irelate.func·004
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:261 +0x35c

goroutine 1 [chan receive]:
main.main()
	/usr/local/src/gocode/src/github.com/brentp/vcfanno/vcfanno.go:157 +0x1ece

goroutine 6 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0xc208080060, 0x72, 0x0, 0x0)
	/usr/local/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208080060, 0x0, 0x0)
	/usr/local/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208080000, 0x0, 0x2aaaaaad4df0, 0xc20802a880)
	/usr/local/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20814a000, 0x47b304, 0x0, 0x0)
	/usr/local/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20814a000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20810a000, 0x2aaaaaad9b48, 0xc20814a000, 0x0, 0x0)
	/usr/local/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20810a000, 0x0, 0x0)
	/usr/local/src/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xa0c9d0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/src/go/src/net/http/server.go:1808 +0xba
main.func·001()
	/usr/local/src/gocode/src/github.com/brentp/vcfanno/vcfanno.go:87 +0x48
created by main.main
	/usr/local/src/gocode/src/github.com/brentp/vcfanno/vcfanno.go:88 +0xe2f

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/usr/local/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 16 [chan receive]:
github.com/brentp/irelate.func·004()
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:200 +0x103
created by github.com/brentp/irelate.PIRelate
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:266 +0x44a

goroutine 34 [chan receive]:
github.com/brentp/irelate.func·005()
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:316 +0x496
created by github.com/brentp/irelate.PIRelate
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:329 +0x4f6

the error file is longer than this. I might be able to email you if you need the entire error log.

**Comment by brentp** [comment] 2015-11-06 13:06
This was caused by a variant in the Kaviar file that had an empty alternate allele (not '.' just empty).
I have added a fix to https://github.com/brentp/vcfgo that will be incorporated into the next release.

**Closed** 2015-11-16 21:36 UTC
